<?php

/**
 * @file
 * Functions to support theming in the AdminKit sub-theme of Adminimnal.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function adminkit_preprocess_html(&$variables) {

  // Add adminimal class to the body.
  $variables['attributes']['class'][] = 'adminkit';

}

function adminkit_preprocess_paragraph(&$variables) {
  $test = '';
}